[build]
  command = "npm run build"
  functions = "dist/netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  
[functions.optimize]
  timeout = 10

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"